export const SIGNUP = 'SIGNUP'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const GET_ORDERS = 'GET_ORDERS'
export const CREATE_ORDER = 'CREATE_ORDER'

export const GET_USER_PHONE_NUMBERS = 'GET_USER_PHONE_NUMBERS'

export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
